package plugin

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

type JsonHttpGen struct {
	suffix string
	ts     TS
}

func NewJsonHttpGen(suffix string, tscfg TS) *JsonHttpGen {
	return &JsonHttpGen{
		suffix: suffix,
		ts:     tscfg,
	}
}

type TS struct {
	ResponseTypeName         string
	ResponseTypeStruct       string
	ImportTsProtoPackageName string
}

func (j *JsonHttpGen) Generate(p *protogen.Plugin) error {
	for _, f := range p.Files {
		if !f.Generate {
			continue
		}
		if err := j.gen(p, f); err != nil {
			return err
		}
	}

	return nil
}

func (j *JsonHttpGen) gen(p *protogen.Plugin, f *protogen.File) error {

	protoFileName := filepath.Base(f.GeneratedFilenamePrefix)
	genFileName := fmt.Sprintf("%s_%s.ts", protoFileName, j.suffix)
	g := p.NewGeneratedFile(genFileName, f.GoImportPath)
	g.P()
	g.P()

	g.P("// Code generated by protoc-gen-" + j.suffix + ". DO NOT EDIT.")
	g.P("// - protoc             ", protocVersion(p))
	if f.Proto.GetOptions().GetDeprecated() {
		g.P("// ", f.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", f.Desc.Path())
	}
	g.P()
	g.P()
	// import ts-proto generate file
	g.P(`import * as pb from "./` + protoFileName + "\";")
	g.P()
	g.P("export type " + j.ts.ResponseTypeName + " = {")
	g.P(strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(j.ts.ResponseTypeStruct, "{"), "}")))
	g.P("}")
	g.P(`
export type RequestHeaders = {
    [key: string]: string;
};

type CallHandler<T> = (
    path: string,
    body: any,
    cfg: T | undefined,
) => Promise<` + j.ts.ResponseTypeName + `>;


export interface CallOptions<T> {
    handler?: CallHandler<T>;
    cfg: T;
}

// for example: 
//
// async function handler<T = any>(
//     path: string,
//	   body: any,
//	   cfg: AxiosRequestConfig<T>,
// ): Promise<` + j.ts.ResponseTypeName + `> {
//	   const resp = await axios.post(path, body, cfg);
//	   return resp.data as ` + j.ts.ResponseTypeName + `;
// }
// 
// const client = new XxxClient(handler);
	`)

	for _, service := range f.Services {
		j.generateClass(g, service)
	}

	return nil
}

func (j *JsonHttpGen) generateClass(g *protogen.GeneratedFile, service *protogen.Service) {
	className := service.Desc.Name() + "Client"
	g.P()
	g.P("export class ", className, "<T> {")
	g.P()
	g.P("    private _baseURL: string;")
	g.P("    private _handler: CallHandler<T>;")
	g.P()
	g.P("    constructor(handler: CallHandler<T>, baseURL?: string) {")
	g.P("        this._handler = handler;")
	g.P("        this._baseURL = baseURL || '';")
	g.P("    }")
	g.P()

	for _, method := range service.Methods {
		if !method.Desc.IsStreamingServer() && !method.Desc.IsStreamingClient() {
			j.generateClassMethod(g, service, method)
		} else {

		}
	}

	g.P("}")
	g.P()
}

func (j *JsonHttpGen) generateClassMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	gwi := func(i ...interface{}) {
		var a = []interface{}{"    "}
		a = append(a, i...)
		g.P(a...)
	}
	gwi("async "+string(method.Desc.Name())+"(req: ", j.ts.ImportTsProtoPackageName, "."+string(method.Input.Desc.Name())+", callOptions?: CallOptions<T>): Promise<"+j.ts.ImportTsProtoPackageName+"."+string(method.Output.Desc.Name())+"> {")
	gwi("    const resp = await this._handler(this._baseURL + '" + formatFullMethodName(service, method) + "', req, callOptions?.cfg)")
	gwi("    if (!resp.meta || resp.meta.code === undefined || resp.meta.message === undefined) {")
	gwi("        throw new Error('unknown response type');")
	gwi("    }")
	gwi("    if (resp.meta.code !== 0) {")
	gwi("        throw new Error(resp.meta.message);")
	gwi("    }")
	gwi("    return " + j.ts.ImportTsProtoPackageName + "." + method.Output.GoIdent.GoName + ".create(resp.data as " + j.ts.ImportTsProtoPackageName + "." + string(method.Output.Desc.Name()) + ")")
	gwi("}")
	gwi()
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func formatFullMethodName(service *protogen.Service, method *protogen.Method) string {
	return fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
}
